# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashtagBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('hashtag_1', models.CharField(max_length=100)),
                ('hashtag_1_cur_typos', models.IntegerField(default=0)),
                ('hashtag_2', models.CharField(max_length=100)),
                ('hashtag_2_cur_typos', models.IntegerField(default=0)),
                ('cur_winner', models.CharField(blank=True, default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.IntegerField()),
            ],
        ),
    ]
